import { IWalletItemDB } from "../@types/types";

const year = new Date().getFullYear();

export const data = {
  gains: [
    {
      type: "wage",
      amount: "1500.00",
      frequency: "Recurrent",
      date: `${year}-01-10`,
    },
    {
      type: "Freelancer",
      amount: "500.00",
      frequency: "Occasional",
      date: `${year}-01-3`,
    },
    {
      type: "wage",
      amount: "1500.00",
      frequency: "Recurrent",
      date: `${year}-02-10`,
    },
    {
      type: "wage",
      amount: "1500.00",
      frequency: "Recurrent",
      date: `${year}-03-10`,
    },
    {
      type: "Freelancer",
      amount: "500.00",
      frequency: "Occasional",
      date: `${year}-03-9`,
    },
    {
      type: "Freelancer",
      amount: "700.00",
      frequency: "Occasional",
      date: `${year}-03-15`,
    },
    {
      type: "wage",
      amount: "1500.00",
      frequency: "Recurrent",
      date: `${year}-04-10`,
    },
    {
      type: "Freelancer",
      amount: "700.00",
      frequency: "Occasional",
      date: `${year}-04-20`,
    },
    {
      type: "wage",
      amount: "1500.00",
      frequency: "Recurrent",
      date: `${year}-05-10`,
    },
    {
      type: "wage",
      amount: "1500.00",
      frequency: "Recurrent",
      date: `${year}-06-10`,
    },
    {
      type: "wage",
      amount: "1500.00",
      frequency: "Recurrent",
      date: `${year}-07-10`,
    },
    {
      type: "Freelancer",
      amount: "700.00",
      frequency: "Occasional",
      date: `${year}-07-05`,
    },
    {
      type: "Freelancer",
      amount: "200.00",
      frequency: "Occasional",
      date: `${year}-07-16`,
    },
    {
      type: "wage",
      amount: "1500.00",
      frequency: "Recurrent",
      date: `${year}-08-10`,
    },
    {
      type: "Freelancer",
      amount: "200.00",
      frequency: "Occasional",
      date: `${year}-08-16`,
    },
    {
      type: "wage",
      amount: "1500.00",
      frequency: "Recurrent",
      date: `${year}-09-10`,
    },
    {
      type: "wage",
      amount: "1500.00",
      frequency: "Recurrent",
      date: `${year}-10-10`,
    },
    {
      type: "wage",
      amount: "1500.00",
      frequency: "Recurrent",
      date: `${year}-11-10`,
    },
    {
      type: "Freelancer",
      amount: "200.00",
      frequency: "Occasional",
      date: `${year}-11-16`,
    },
    {
      type: "wage",
      amount: "1500.00",
      frequency: "Recurrent",
      date: `${year}-12-10`,
    },
  ] as IWalletItemDB,
  expenses: [
    {
      type: "Basic expenses",
      amount: "500",
      frequency: "Recurrent",
      date: `${year}-01-05`,
    },
    {
      type: "Ticket",
      amount: "900",
      frequency: "Occasional",
      date: `${year}-01-15`,
    },
    {
      type: "Basic expenses",
      amount: "540",
      frequency: "Recurrent",
      date: `${year}-02-05`,
    },
    {
      type: "Basic expenses",
      amount: "700",
      frequency: "Recurrent",
      date: `${year}-03-05`,
    },
    {
      type: "Clothes",
      amount: "1200",
      frequency: "Occasional",
      date: `${year}-03-10`,
    },
    {
      type: "Basic expenses",
      amount: "500",
      frequency: "Recurrent",
      date: `${year}-04-05`,
    },
    {
      type: "Ticket",
      amount: "800",
      frequency: "Occasional",
      date: `${year}-04-10`,
    },
    {
      type: "Basic expenses",
      amount: "650",
      frequency: "Recurrent",
      date: `${year}-05-05`,
    },
    {
      type: "Food",
      amount: "300",
      frequency: "Occasional",
      date: `${year}-05-15`,
    },
    {
      type: "Basic expenses",
      amount: "720",
      frequency: "Recurrent",
      date: `${year}-06-05`,
    },
    {
      type: "Clothes",
      amount: "1500",
      frequency: "Occasional",
      date: `${year}-06-10`,
    },
    {
      type: "Basic expenses",
      amount: "300",
      frequency: "Recurrent",
      date: `${year}-07-05`,
    },
    {
      type: "Ticket",
      amount: "500",
      frequency: "Occasional",
      date: `${year}-07-10`,
    },
    {
      type: "Basic expenses",
      amount: "660",
      frequency: "Recurrent",
      date: `${year}-08-05`,
    },
    {
      type: "Basic expenses",
      amount: "670",
      frequency: "Recurrent",
      date: `${year}-09-05`,
    },
    {
      type: "Clothes",
      amount: "800",
      frequency: "Occasional",
      date: `${year}-09-10`,
    },
    {
      type: "Ticket",
      amount: "900",
      frequency: "Occasional",
      date: `${year}-09-10`,
    },
    {
      type: "Basic expenses",
      amount: "800",
      frequency: "Recurrent",
      date: `${year}-10-05`,
    },
    {
      type: "Basic expenses",
      amount: "500",
      frequency: "Recurrent",
      date: `${year}-11-05`,
    },
    {
      type: "Clothes",
      amount: "1500",
      frequency: "Occasional",
      date: `${year}-11-10`,
    },
    {
      type: "Basic expenses",
      amount: "580",
      frequency: "Recurrent",
      date: `${year}-12-05`,
    },
  ] as IWalletItemDB,
};
